### Initial GET
GET http://localhost:3001/api

### Login POST
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "123456"
}

### Logout
GET http://localhost:3001/api/auth/logout


### Solicitudes GET
GET http://localhost:3001/api/solicitudes-inmuebles