export const formatMoney = (
  value: number,
  locale = "es-MX",
  currency = "MXN"
): string => {
  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
};
export const STATES_NAMES_BY_ID: Record<number, string> = {
  1: "Aguascalientes",
  2: "Baja California",
  3: "Baja California Sur",
  4: "Campeche",
  5: "Chiapas",
  6: "Chihuahua",
  7: "Ciudad de México",
  8: "Coahuila de Zaragoza",
  9: "Colima",
  10: "Durango",
  11: "Guanajuato",
  12: "Guerrero",
  13: "Hidalgo",
  14: "Jalisco",
  15: "México",
  16: "Michoacán de Ocampo",
  17: "Morelos",
  18: "Nayarit",
  19: "Nuevo León",
  20: "Oaxaca",
  21: "Puebla",
  22: "Querétaro",
  23: "Quintana Roo",
  24: "San Luis Potosí",
  25: "Sinaloa",
  26: "Sonora",
  27: "Tabasco",
  28: "Tamaulipas",
  29: "Tlaxcala",
  30: "Veracruz de Ignacio de la Llave",
  31: "Yucatán",
  32: "Zacatecas",
};

export const CITIES_NAMES_BY_ID: Record<number, string> = {
  1: "Aguascalientes",
  2: "Calvillo",
  3: "Jesús María",
  4: "Mexicali",
  5: "Tijuana",
  6: "Ensenada",
  7: "La Paz",
  8: "Los Cabos",
  9: "Loreto",
  10: "Campeche",
  11: "Ciudad del Carmen",
  12: "Champotón",
  13: "Tuxtla Gutiérrez",
  14: "San Cristóbal de las Casas",
  15: "Tapachula",
  16: "Chihuahua",
  17: "Ciudad Juárez",
  18: "Delicias",
  19: "Ciudad de México",
  20: "Saltillo",
  21: "Torreón",
  22: "Monclova",
  23: "Colima",
  24: "Manzanillo",
  25: "Tecomán",
  26: "Durango",
  27: "Gómez Palacio",
  28: "Lerdo",
  29: "Guanajuato",
  30: "León",
  31: "Irapuato",
  32: "Chilpancingo",
  33: "Acapulco",
  34: "Iguala",
  35: "Pachuca",
  36: "Tulancingo",
  37: "Tula",
  38: "Guadalajara",
  39: "Zapopan",
  40: "Puerto Vallarta",
  41: "Toluca",
  42: "Ecatepec",
  43: "Naucalpan",
  44: "Morelia",
  45: "Uruapan",
  46: "Zamora",
  47: "Cuernavaca",
  48: "Cuautla",
  49: "Jiutepec",
  50: "Tepic",
  51: "Bahía de Banderas",
  52: "Compostela",
  53: "Monterrey",
  54: "San Nicolás de los Garza",
  55: "Guadalupe",
  56: "Oaxaca de Juárez",
  57: "Salina Cruz",
  58: "Juchitán",
  59: "Puebla",
  60: "Tehuacán",
  61: "San Martín Texmelucan",
  62: "Santiago de Querétaro",
  63: "San Juan del Río",
  64: "El Marqués",
  65: "Cancún",
  66: "Playa del Carmen",
  67: "Chetumal",
  68: "San Luis Potosí",
  69: "Ciudad Valles",
  70: "Matehuala",
  71: "Culiacán",
  72: "Mazatlán",
  73: "Los Mochis",
  74: "Hermosillo",
  75: "Ciudad Obregón",
  76: "Nogales",
  77: "Villahermosa",
  78: "Cárdenas",
  79: "Comalcalco",
  80: "Ciudad Victoria",
  81: "Reynosa",
  82: "Matamoros",
  83: "Tlaxcala",
  84: "Apizaco",
  85: "Huamantla",
  86: "Xalapa",
  87: "Veracruz",
  88: "Coatzacoalcos",
  89: "Mérida",
  90: "Valladolid",
  91: "Tizimín",
  92: "Zacatecas",
  93: "Fresnillo",
  94: "Guadalupe",
};

export const NAME_TYPE_PROPERTY_BY_ID: Record<number, string> = {
  1: "Casa",
  2: "Departamento",
  3: "Terreno",
  4: "Oficina",
  5: "Local Comercial",
  6: "Bodega",
  7: "Loft",
  8: "Lote",
  9: "Nave industrial",
};

export const NAME_TYPE_ACTION_BY_ID: Record<number, string> = {
  1: "Venta",
  2: "Renta",
  3: "Traspaso",
  4: "Pre-Venta",
  5: "Aportacion",
  6: "Remate",
};
